#
# application.yml — главный конфигурационный файл Spring Boot.
#
#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
      dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://localhost:3306/bank_cards_db
    username: root
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver

encoding:
  password: test
  salt: korablecrushenie

app:
  jwt-secret: yourSecretKeyForJWTSigningMustBeAtLeast512BitsLongakjkjfkjhejkhdkjfhkjhwjkhfkjhwekjvhkjwhkjhrkjvhkjrh
  jwt-expiration-ms: 86400000
#  liquibase:
#    enabled: true
#    change-log: classpath:db/migration/db.changelog-master.yaml
#    user: ${spring.datasource.username}
#    password: ${spring.datasource.password}
#    url: ${spring.datasource.url}
#    default-schema: public
#    contexts: dev